
services:
  db:
    image: postgres
    container_name: weather-db
    environment:
      POSTGRES_DB: weatherdb
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d weatherdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: weather-app
    ports:
      - "8080:8080"
    environment:
      # We use 'db' here because Docker Compose lets them talk by service name!
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/weatherdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      WEATHER_API_KEY: 723c8b1bcdb897910eda49e725848e8a
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: