## Local Postgres Connection
#spring.datasource.url=jdbc:postgresql://localhost:5432/weatherdb
#spring.datasource.username=postgres
#spring.datasource.password=password
#
## Standard Hibernate Settings
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#

# Updated for Docker-to-Docker communication
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/weatherdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
# Useful for debugging local database calls
spring.jpa.show-sql=true